import type { AirportRecord } from "@/lib/airports/types";

export const airports: AirportRecord[] = [
  {
    iata: "MAD",
    nameEn: "Adolfo Suárez Madrid–Barajas Airport",
    nameEs: "Aeropuerto Adolfo Suárez Madrid-Barajas",
    shortNameEn: "Madrid Airport",
    shortNameEs: "Aeropuerto de Madrid",
    cityEn: "Madrid",
    cityEs: "Madrid",
    regionEn: "Community of Madrid",
    regionEs: "Comunidad de Madrid",
    slugEn: "madrid-airport-transfer",
    slugEs: "traslado-aeropuerto-madrid",
    isMajor: true,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Madrid City Centre", nameEs: "Centro de Madrid", driveTime: "30 min" },
      { nameEn: "Toledo", nameEs: "Toledo", driveTime: "1 hr" },
      { nameEn: "Segovia", nameEs: "Segovia", driveTime: "1 hr 20 min" },
    ],
    nearbyCities: [
      { nameEn: "Alcalá de Henares", nameEs: "Alcalá de Henares", driveTime: "20 min" },
      { nameEn: "Getafe", nameEs: "Getafe", driveTime: "35 min" },
      { nameEn: "Alcobendas", nameEs: "Alcobendas", driveTime: "20 min" },
    ],
    nearbyAirports: [],
    imageSeed: 0,
  },
  {
    iata: "BCN",
    nameEn: "Josep Tarradellas Barcelona–El Prat Airport",
    nameEs: "Aeropuerto Josep Tarradellas Barcelona-El Prat",
    shortNameEn: "Barcelona Airport",
    shortNameEs: "Aeropuerto de Barcelona",
    cityEn: "Barcelona",
    cityEs: "Barcelona",
    regionEn: "Catalonia",
    regionEs: "Cataluña",
    slugEn: "barcelona-airport-transfer",
    slugEs: "traslado-aeropuerto-barcelona",
    isMajor: true,
    islandGroup: null,
    hasCruisePort: true,
    destinations: [
      { nameEn: "Barcelona City Centre", nameEs: "Centro de Barcelona", driveTime: "20 min" },
      { nameEn: "Sitges", nameEs: "Sitges", driveTime: "30 min" },
      { nameEn: "Girona", nameEs: "Girona", driveTime: "1 hr 10 min" },
    ],
    nearbyCities: [
      { nameEn: "L'Hospitalet de Llobregat", nameEs: "L'Hospitalet de Llobregat", driveTime: "15 min" },
      { nameEn: "Badalona", nameEs: "Badalona", driveTime: "30 min" },
      { nameEn: "Castelldefels", nameEs: "Castelldefels", driveTime: "15 min" },
    ],
    nearbyAirports: [{ iata: "GRO", driveTime: "1 hr 10 min" }, { iata: "REU", driveTime: "1 hr 15 min" }],
    imageSeed: 1,
  },
  {
    iata: "AGP",
    nameEn: "Málaga–Costa del Sol Airport",
    nameEs: "Aeropuerto de Málaga-Costa del Sol",
    shortNameEn: "Málaga Airport",
    shortNameEs: "Aeropuerto de Málaga",
    cityEn: "Málaga",
    cityEs: "Málaga",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    slugEn: "malaga-airport-transfer",
    slugEs: "traslado-aeropuerto-malaga",
    isMajor: true,
    islandGroup: null,
    hasCruisePort: true,
    destinations: [
      { nameEn: "Marbella", nameEs: "Marbella", driveTime: "45 min" },
      { nameEn: "Málaga City Centre", nameEs: "Centro de Málaga", driveTime: "15 min" },
      { nameEn: "Estepona", nameEs: "Estepona", driveTime: "1 hr" },
    ],
    nearbyCities: [
      { nameEn: "Torremolinos", nameEs: "Torremolinos", driveTime: "10 min" },
      { nameEn: "Benalmádena", nameEs: "Benalmádena", driveTime: "15 min" },
      { nameEn: "Fuengirola", nameEs: "Fuengirola", driveTime: "25 min" },
    ],
    nearbyAirports: [{ iata: "GIB", driveTime: "1 hr 20 min" }],
    imageSeed: 2,
  },
  {
    iata: "ALC",
    nameEn: "Alicante–Elche Miguel Hernández Airport",
    nameEs: "Aeropuerto de Alicante-Elche Miguel Hernández",
    shortNameEn: "Alicante Airport",
    shortNameEs: "Aeropuerto de Alicante",
    cityEn: "Alicante",
    cityEs: "Alicante",
    regionEn: "Valencian Community",
    regionEs: "Comunidad Valenciana",
    slugEn: "alicante-airport-transfer",
    slugEs: "traslado-aeropuerto-alicante",
    isMajor: true,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Benidorm", nameEs: "Benidorm", driveTime: "40 min" },
      { nameEn: "Alicante City Centre", nameEs: "Centro de Alicante", driveTime: "20 min" },
      { nameEn: "Torrevieja", nameEs: "Torrevieja", driveTime: "35 min" },
    ],
    nearbyCities: [
      { nameEn: "Elche", nameEs: "Elche", driveTime: "15 min" },
      { nameEn: "San Juan de Alicante", nameEs: "San Juan de Alicante", driveTime: "20 min" },
      { nameEn: "Santa Pola", nameEs: "Santa Pola", driveTime: "20 min" },
    ],
    nearbyAirports: [{ iata: "MJV", driveTime: "1 hr" }],
    imageSeed: 3,
  },
  {
    iata: "VLC",
    nameEn: "Valencia Airport",
    nameEs: "Aeropuerto de Valencia",
    shortNameEn: "Valencia Airport",
    shortNameEs: "Aeropuerto de Valencia",
    cityEn: "Valencia",
    cityEs: "Valencia",
    regionEn: "Valencian Community",
    regionEs: "Comunidad Valenciana",
    slugEn: "valencia-airport-transfer",
    slugEs: "traslado-aeropuerto-valencia",
    isMajor: true,
    islandGroup: null,
    hasCruisePort: true,
    destinations: [
      { nameEn: "Valencia City Centre", nameEs: "Centro de Valencia", driveTime: "20 min" },
      { nameEn: "Sagunto", nameEs: "Sagunto", driveTime: "35 min" },
      { nameEn: "Xàtiva", nameEs: "Xàtiva", driveTime: "45 min" },
    ],
    nearbyCities: [
      { nameEn: "Manises", nameEs: "Manises", driveTime: "5 min" },
      { nameEn: "Mislata", nameEs: "Mislata", driveTime: "15 min" },
      { nameEn: "Torrent", nameEs: "Torrent", driveTime: "15 min" },
    ],
    nearbyAirports: [],
    imageSeed: 4,
  },
  {
    iata: "SVQ",
    nameEn: "Seville Airport",
    nameEs: "Aeropuerto de Sevilla",
    shortNameEn: "Seville Airport",
    shortNameEs: "Aeropuerto de Sevilla",
    cityEn: "Seville",
    cityEs: "Sevilla",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    slugEn: "seville-airport-transfer",
    slugEs: "traslado-aeropuerto-sevilla",
    isMajor: true,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Seville City Centre", nameEs: "Centro de Sevilla", driveTime: "20 min" },
      { nameEn: "Córdoba", nameEs: "Córdoba", driveTime: "1 hr 30 min" },
      { nameEn: "Carmona", nameEs: "Carmona", driveTime: "25 min" },
    ],
    nearbyCities: [
      { nameEn: "La Rinconada", nameEs: "La Rinconada", driveTime: "10 min" },
      { nameEn: "Alcalá de Guadaíra", nameEs: "Alcalá de Guadaíra", driveTime: "25 min" },
      { nameEn: "Dos Hermanas", nameEs: "Dos Hermanas", driveTime: "30 min" },
    ],
    nearbyAirports: [],
    imageSeed: 5,
  },
  {
    iata: "BIO",
    nameEn: "Bilbao Airport",
    nameEs: "Aeropuerto de Bilbao",
    shortNameEn: "Bilbao Airport",
    shortNameEs: "Aeropuerto de Bilbao",
    cityEn: "Bilbao",
    cityEs: "Bilbao",
    regionEn: "Basque Country",
    regionEs: "País Vasco",
    slugEn: "bilbao-airport-transfer",
    slugEs: "traslado-aeropuerto-bilbao",
    isMajor: true,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Bilbao City Centre", nameEs: "Centro de Bilbao", driveTime: "20 min" },
      { nameEn: "San Sebastián", nameEs: "San Sebastián", driveTime: "1 hr" },
      { nameEn: "Vitoria-Gasteiz", nameEs: "Vitoria-Gasteiz", driveTime: "1 hr" },
    ],
    nearbyCities: [
      { nameEn: "Getxo", nameEs: "Getxo", driveTime: "25 min" },
      { nameEn: "Barakaldo", nameEs: "Barakaldo", driveTime: "20 min" },
      { nameEn: "Durango", nameEs: "Durango", driveTime: "30 min" },
    ],
    nearbyAirports: [{ iata: "EAS", driveTime: "1 hr" }],
    imageSeed: 6,
  },
  {
    iata: "PMI",
    nameEn: "Palma de Mallorca Airport",
    nameEs: "Aeropuerto de Palma de Mallorca",
    shortNameEn: "Palma Airport",
    shortNameEs: "Aeropuerto de Palma",
    cityEn: "Palma de Mallorca",
    cityEs: "Palma de Mallorca",
    regionEn: "Balearic Islands",
    regionEs: "Islas Baleares",
    slugEn: "palma-airport-transfer",
    slugEs: "traslado-aeropuerto-palma",
    isMajor: true,
    islandGroup: "balearic",
    hasCruisePort: true,
    destinations: [
      { nameEn: "Palma City Centre", nameEs: "Centro de Palma", driveTime: "15 min" },
      { nameEn: "Alcúdia", nameEs: "Alcúdia", driveTime: "50 min" },
      { nameEn: "Sóller", nameEs: "Sóller", driveTime: "40 min" },
    ],
    nearbyCities: [
      { nameEn: "Llucmajor", nameEs: "Llucmajor", driveTime: "20 min" },
      { nameEn: "Manacor", nameEs: "Manacor", driveTime: "45 min" },
      { nameEn: "Inca", nameEs: "Inca", driveTime: "30 min" },
    ],
    nearbyAirports: [],
    imageSeed: 7,
  },
  {
    iata: "IBZ",
    nameEn: "Ibiza Airport",
    nameEs: "Aeropuerto de Ibiza",
    shortNameEn: "Ibiza Airport",
    shortNameEs: "Aeropuerto de Ibiza",
    cityEn: "Ibiza",
    cityEs: "Ibiza",
    regionEn: "Balearic Islands",
    regionEs: "Islas Baleares",
    slugEn: "ibiza-airport-transfer",
    slugEs: "traslado-aeropuerto-ibiza",
    isMajor: true,
    islandGroup: "balearic",
    hasCruisePort: true,
    destinations: [
      { nameEn: "Ibiza Town", nameEs: "Ciudad de Ibiza", driveTime: "15 min" },
      { nameEn: "San Antonio", nameEs: "San Antonio", driveTime: "25 min" },
      { nameEn: "Santa Eulalia", nameEs: "Santa Eulalia", driveTime: "25 min" },
    ],
    nearbyCities: [
      { nameEn: "Sant Josep de sa Talaia", nameEs: "Sant Josep de sa Talaia", driveTime: "10 min" },
      { nameEn: "Jesús", nameEs: "Jesús", driveTime: "15 min" },
    ],
    nearbyAirports: [],
    imageSeed: 8,
  },
  {
    iata: "MAH",
    nameEn: "Menorca Airport",
    nameEs: "Aeropuerto de Menorca",
    shortNameEn: "Menorca Airport",
    shortNameEs: "Aeropuerto de Menorca",
    cityEn: "Mahón",
    cityEs: "Mahón",
    regionEn: "Balearic Islands",
    regionEs: "Islas Baleares",
    slugEn: "menorca-airport-transfer",
    slugEs: "traslado-aeropuerto-menorca",
    isMajor: false,
    islandGroup: "balearic",
    hasCruisePort: true,
    destinations: [
      { nameEn: "Mahón", nameEs: "Mahón", driveTime: "10 min" },
      { nameEn: "Ciutadella", nameEs: "Ciutadella", driveTime: "45 min" },
      { nameEn: "Es Castell", nameEs: "Es Castell", driveTime: "15 min" },
    ],
    nearbyCities: [
      { nameEn: "Alaior", nameEs: "Alaior", driveTime: "15 min" },
      { nameEn: "Sant Lluís", nameEs: "Sant Lluís", driveTime: "15 min" },
    ],
    nearbyAirports: [],
    imageSeed: 9,
  },
  {
    iata: "TFS",
    nameEn: "Tenerife South Airport",
    nameEs: "Aeropuerto de Tenerife Sur",
    shortNameEn: "Tenerife South Airport",
    shortNameEs: "Aeropuerto de Tenerife Sur",
    cityEn: "Granadilla de Abona",
    cityEs: "Granadilla de Abona",
    regionEn: "Canary Islands",
    regionEs: "Islas Canarias",
    slugEn: "tenerife-south-airport-transfer",
    slugEs: "traslado-aeropuerto-tenerife-sur",
    isMajor: true,
    islandGroup: "canary",
    hasCruisePort: false,
    destinations: [
      { nameEn: "Costa Adeje", nameEs: "Costa Adeje", driveTime: "20 min" },
      { nameEn: "Los Cristianos", nameEs: "Los Cristianos", driveTime: "15 min" },
      { nameEn: "Santa Cruz de Tenerife", nameEs: "Santa Cruz de Tenerife", driveTime: "1 hr" },
    ],
    nearbyCities: [
      { nameEn: "Playa de las Américas", nameEs: "Playa de las Américas", driveTime: "20 min" },
      { nameEn: "Arona", nameEs: "Arona", driveTime: "15 min" },
    ],
    nearbyAirports: [{ iata: "TFN", driveTime: "1 hr" }],
    imageSeed: 10,
  },
  {
    iata: "TFN",
    nameEn: "Tenerife North Airport",
    nameEs: "Aeropuerto de Tenerife Norte",
    shortNameEn: "Tenerife North Airport",
    shortNameEs: "Aeropuerto de Tenerife Norte",
    cityEn: "La Laguna",
    cityEs: "La Laguna",
    regionEn: "Canary Islands",
    regionEs: "Islas Canarias",
    slugEn: "tenerife-north-airport-transfer",
    slugEs: "traslado-aeropuerto-tenerife-norte",
    isMajor: false,
    islandGroup: "canary",
    hasCruisePort: false,
    destinations: [
      { nameEn: "Santa Cruz de Tenerife", nameEs: "Santa Cruz de Tenerife", driveTime: "20 min" },
      { nameEn: "San Cristóbal de La Laguna", nameEs: "San Cristóbal de La Laguna", driveTime: "10 min" },
      { nameEn: "Puerto de la Cruz", nameEs: "Puerto de la Cruz", driveTime: "30 min" },
    ],
    nearbyCities: [
      { nameEn: "Tacoronte", nameEs: "Tacoronte", driveTime: "15 min" },
      { nameEn: "El Rosario", nameEs: "El Rosario", driveTime: "10 min" },
    ],
    nearbyAirports: [{ iata: "TFS", driveTime: "1 hr" }],
    imageSeed: 11,
  },
  {
    iata: "LPA",
    nameEn: "Gran Canaria Airport",
    nameEs: "Aeropuerto de Gran Canaria",
    shortNameEn: "Gran Canaria Airport",
    shortNameEs: "Aeropuerto de Gran Canaria",
    cityEn: "Las Palmas de Gran Canaria",
    cityEs: "Las Palmas de Gran Canaria",
    regionEn: "Canary Islands",
    regionEs: "Islas Canarias",
    slugEn: "gran-canaria-airport-transfer",
    slugEs: "traslado-aeropuerto-gran-canaria",
    isMajor: true,
    islandGroup: "canary",
    hasCruisePort: true,
    destinations: [
      { nameEn: "Las Palmas de Gran Canaria", nameEs: "Las Palmas de Gran Canaria", driveTime: "25 min" },
      { nameEn: "Maspalomas", nameEs: "Maspalomas", driveTime: "30 min" },
      { nameEn: "Puerto Rico", nameEs: "Puerto Rico", driveTime: "40 min" },
    ],
    nearbyCities: [
      { nameEn: "Telde", nameEs: "Telde", driveTime: "10 min" },
      { nameEn: "Ingenio", nameEs: "Ingenio", driveTime: "15 min" },
    ],
    nearbyAirports: [],
    imageSeed: 12,
  },
  {
    iata: "ACE",
    nameEn: "Lanzarote Airport",
    nameEs: "Aeropuerto de Lanzarote",
    shortNameEn: "Lanzarote Airport",
    shortNameEs: "Aeropuerto de Lanzarote",
    cityEn: "Arrecife",
    cityEs: "Arrecife",
    regionEn: "Canary Islands",
    regionEs: "Islas Canarias",
    slugEn: "lanzarote-airport-transfer",
    slugEs: "traslado-aeropuerto-lanzarote",
    isMajor: false,
    islandGroup: "canary",
    hasCruisePort: true,
    destinations: [
      { nameEn: "Arrecife", nameEs: "Arrecife", driveTime: "10 min" },
      { nameEn: "Puerto del Carmen", nameEs: "Puerto del Carmen", driveTime: "15 min" },
      { nameEn: "Playa Blanca", nameEs: "Playa Blanca", driveTime: "30 min" },
    ],
    nearbyCities: [
      { nameEn: "San Bartolomé", nameEs: "San Bartolomé", driveTime: "10 min" },
      { nameEn: "Tías", nameEs: "Tías", driveTime: "15 min" },
    ],
    nearbyAirports: [],
    imageSeed: 13,
  },
  {
    iata: "FUE",
    nameEn: "Fuerteventura Airport",
    nameEs: "Aeropuerto de Fuerteventura",
    shortNameEn: "Fuerteventura Airport",
    shortNameEs: "Aeropuerto de Fuerteventura",
    cityEn: "Puerto del Rosario",
    cityEs: "Puerto del Rosario",
    regionEn: "Canary Islands",
    regionEs: "Islas Canarias",
    slugEn: "fuerteventura-airport-transfer",
    slugEs: "traslado-aeropuerto-fuerteventura",
    isMajor: false,
    islandGroup: "canary",
    hasCruisePort: false,
    destinations: [
      { nameEn: "Puerto del Rosario", nameEs: "Puerto del Rosario", driveTime: "10 min" },
      { nameEn: "Caleta de Fuste", nameEs: "Caleta de Fuste", driveTime: "10 min" },
      { nameEn: "Corralejo", nameEs: "Corralejo", driveTime: "35 min" },
    ],
    nearbyCities: [
      { nameEn: "Antigua", nameEs: "Antigua", driveTime: "15 min" },
    ],
    nearbyAirports: [],
    imageSeed: 14,
  },
  {
    iata: "GRO",
    nameEn: "Girona–Costa Brava Airport",
    nameEs: "Aeropuerto de Girona-Costa Brava",
    shortNameEn: "Girona Airport",
    shortNameEs: "Aeropuerto de Girona",
    cityEn: "Girona",
    cityEs: "Girona",
    regionEn: "Catalonia",
    regionEs: "Cataluña",
    slugEn: "girona-airport-transfer",
    slugEs: "traslado-aeropuerto-girona",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Girona City Centre", nameEs: "Centro de Girona", driveTime: "20 min" },
      { nameEn: "Costa Brava", nameEs: "Costa Brava", driveTime: "40 min" },
      { nameEn: "Barcelona", nameEs: "Barcelona", driveTime: "1 hr 10 min" },
    ],
    nearbyCities: [
      { nameEn: "Figueres", nameEs: "Figueres", driveTime: "30 min" },
      { nameEn: "Salt", nameEs: "Salt", driveTime: "20 min" },
    ],
    nearbyAirports: [{ iata: "BCN", driveTime: "1 hr 10 min" }, { iata: "REU", driveTime: "2 hrs" }],
    imageSeed: 15,
  },
  {
    iata: "REU",
    nameEn: "Reus Airport",
    nameEs: "Aeropuerto de Reus",
    shortNameEn: "Reus Airport",
    shortNameEs: "Aeropuerto de Reus",
    cityEn: "Reus",
    cityEs: "Reus",
    regionEn: "Catalonia",
    regionEs: "Cataluña",
    slugEn: "reus-airport-transfer",
    slugEs: "traslado-aeropuerto-reus",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Salou", nameEs: "Salou", driveTime: "15 min" },
      { nameEn: "PortAventura", nameEs: "PortAventura", driveTime: "15 min" },
      { nameEn: "Tarragona", nameEs: "Tarragona", driveTime: "20 min" },
    ],
    nearbyCities: [
      { nameEn: "Cambrils", nameEs: "Cambrils", driveTime: "20 min" },
    ],
    nearbyAirports: [{ iata: "BCN", driveTime: "1 hr 15 min" }],
    imageSeed: 16,
  },
  {
    iata: "RMU",
    nameEn: "Murcia International Airport",
    nameEs: "Aeropuerto Internacional de la Región de Murcia",
    shortNameEn: "Murcia Airport",
    shortNameEs: "Aeropuerto de Murcia",
    cityEn: "Murcia",
    cityEs: "Murcia",
    regionEn: "Region of Murcia",
    regionEs: "Región de Murcia",
    slugEn: "murcia-airport-transfer",
    slugEs: "traslado-aeropuerto-murcia",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Murcia City Centre", nameEs: "Centro de Murcia", driveTime: "30 min" },
      { nameEn: "Cartagena", nameEs: "Cartagena", driveTime: "35 min" },
      { nameEn: "La Manga", nameEs: "La Manga", driveTime: "50 min" },
    ],
    nearbyCities: [
      { nameEn: "Fortuna", nameEs: "Fortuna", driveTime: "15 min" },
    ],
    nearbyAirports: [{ iata: "ALC", driveTime: "1 hr" }],
    imageSeed: 17,
  },
  {
    iata: "OVD",
    nameEn: "Asturias Airport",
    nameEs: "Aeropuerto de Asturias",
    shortNameEn: "Asturias Airport",
    shortNameEs: "Aeropuerto de Asturias",
    cityEn: "Oviedo",
    cityEs: "Oviedo",
    regionEn: "Asturias",
    regionEs: "Asturias",
    slugEn: "asturias-airport-transfer",
    slugEs: "traslado-aeropuerto-asturias",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Oviedo", nameEs: "Oviedo", driveTime: "30 min" },
      { nameEn: "Gijón", nameEs: "Gijón", driveTime: "25 min" },
      { nameEn: "Avilés", nameEs: "Avilés", driveTime: "15 min" },
    ],
    nearbyCities: [
      { nameEn: "Avilés", nameEs: "Avilés", driveTime: "15 min" },
    ],
    nearbyAirports: [],
    imageSeed: 18,
  },
  {
    iata: "SCQ",
    nameEn: "Santiago–Rosalía de Castro Airport",
    nameEs: "Aeropuerto de Santiago-Rosalía de Castro",
    shortNameEn: "Santiago Airport",
    shortNameEs: "Aeropuerto de Santiago",
    cityEn: "Santiago de Compostela",
    cityEs: "Santiago de Compostela",
    regionEn: "Galicia",
    regionEs: "Galicia",
    slugEn: "santiago-airport-transfer",
    slugEs: "traslado-aeropuerto-santiago",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Santiago de Compostela", nameEs: "Santiago de Compostela", driveTime: "20 min" },
      { nameEn: "A Coruña", nameEs: "A Coruña", driveTime: "50 min" },
      { nameEn: "Padrón", nameEs: "Padrón", driveTime: "25 min" },
    ],
    nearbyCities: [
      { nameEn: "Ames", nameEs: "Ames", driveTime: "15 min" },
    ],
    nearbyAirports: [{ iata: "LCG", driveTime: "50 min" }, { iata: "VGO", driveTime: "1 hr" }],
    imageSeed: 19,
  },
  {
    iata: "VGO",
    nameEn: "Vigo Airport",
    nameEs: "Aeropuerto de Vigo",
    shortNameEn: "Vigo Airport",
    shortNameEs: "Aeropuerto de Vigo",
    cityEn: "Vigo",
    cityEs: "Vigo",
    regionEn: "Galicia",
    regionEs: "Galicia",
    slugEn: "vigo-airport-transfer",
    slugEs: "traslado-aeropuerto-vigo",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: true,
    destinations: [
      { nameEn: "Vigo City Centre", nameEs: "Centro de Vigo", driveTime: "15 min" },
      { nameEn: "Baiona", nameEs: "Baiona", driveTime: "35 min" },
      { nameEn: "Pontevedra", nameEs: "Pontevedra", driveTime: "30 min" },
    ],
    nearbyCities: [
      { nameEn: "Redondela", nameEs: "Redondela", driveTime: "15 min" },
    ],
    nearbyAirports: [{ iata: "SCQ", driveTime: "1 hr" }],
    imageSeed: 20,
  },
  {
    iata: "LCG",
    nameEn: "A Coruña Airport",
    nameEs: "Aeropuerto de A Coruña",
    shortNameEn: "A Coruña Airport",
    shortNameEs: "Aeropuerto de A Coruña",
    cityEn: "A Coruña",
    cityEs: "A Coruña",
    regionEn: "Galicia",
    regionEs: "Galicia",
    slugEn: "a-coruna-airport-transfer",
    slugEs: "traslado-aeropuerto-a-coruna",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: true,
    destinations: [
      { nameEn: "A Coruña City Centre", nameEs: "Centro de A Coruña", driveTime: "15 min" },
      { nameEn: "Santiago de Compostela", nameEs: "Santiago de Compostela", driveTime: "50 min" },
    ],
    nearbyCities: [
      { nameEn: "Culleredo", nameEs: "Culleredo", driveTime: "10 min" },
    ],
    nearbyAirports: [{ iata: "SCQ", driveTime: "50 min" }],
    imageSeed: 21,
  },
  {
    iata: "ZAZ",
    nameEn: "Zaragoza Airport",
    nameEs: "Aeropuerto de Zaragoza",
    shortNameEn: "Zaragoza Airport",
    shortNameEs: "Aeropuerto de Zaragoza",
    cityEn: "Zaragoza",
    cityEs: "Zaragoza",
    regionEn: "Aragon",
    regionEs: "Aragón",
    slugEn: "zaragoza-airport-transfer",
    slugEs: "traslado-aeropuerto-zaragoza",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Zaragoza City Centre", nameEs: "Centro de Zaragoza", driveTime: "15 min" },
    ],
    nearbyCities: [
      { nameEn: "Utebo", nameEs: "Utebo", driveTime: "10 min" },
    ],
    nearbyAirports: [],
    imageSeed: 22,
  },
  {
    iata: "XRY",
    nameEn: "Jerez Airport",
    nameEs: "Aeropuerto de Jerez",
    shortNameEn: "Jerez Airport",
    shortNameEs: "Aeropuerto de Jerez",
    cityEn: "Jerez de la Frontera",
    cityEs: "Jerez de la Frontera",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    slugEn: "jerez-airport-transfer",
    slugEs: "traslado-aeropuerto-jerez",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Jerez de la Frontera", nameEs: "Jerez de la Frontera", driveTime: "15 min" },
      { nameEn: "Cádiz", nameEs: "Cádiz", driveTime: "40 min" },
      { nameEn: "El Puerto de Santa María", nameEs: "El Puerto de Santa María", driveTime: "20 min" },
    ],
    nearbyCities: [
      { nameEn: "Sanlúcar de Barrameda", nameEs: "Sanlúcar de Barrameda", driveTime: "25 min" },
    ],
    nearbyAirports: [],
    imageSeed: 23,
  },
  {
    iata: "LEI",
    nameEn: "Almería Airport",
    nameEs: "Aeropuerto de Almería",
    shortNameEn: "Almería Airport",
    shortNameEs: "Aeropuerto de Almería",
    cityEn: "Almería",
    cityEs: "Almería",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    slugEn: "almeria-airport-transfer",
    slugEs: "traslado-aeropuerto-almeria",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: true,
    destinations: [
      { nameEn: "Almería City Centre", nameEs: "Centro de Almería", driveTime: "15 min" },
      { nameEn: "Roquetas de Mar", nameEs: "Roquetas de Mar", driveTime: "25 min" },
    ],
    nearbyCities: [
      { nameEn: "El Ejido", nameEs: "El Ejido", driveTime: "30 min" },
    ],
    nearbyAirports: [],
    imageSeed: 24,
  },
  {
    iata: "GRX",
    nameEn: "Granada–Jaén Airport",
    nameEs: "Aeropuerto de Granada-Jaén",
    shortNameEn: "Granada Airport",
    shortNameEs: "Aeropuerto de Granada",
    cityEn: "Granada",
    cityEs: "Granada",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    slugEn: "granada-airport-transfer",
    slugEs: "traslado-aeropuerto-granada",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Granada City Centre", nameEs: "Centro de Granada", driveTime: "30 min" },
      { nameEn: "Alhambra", nameEs: "Alhambra", driveTime: "35 min" },
    ],
    nearbyCities: [
      { nameEn: "Santa Fe", nameEs: "Santa Fe", driveTime: "10 min" },
    ],
    nearbyAirports: [],
    imageSeed: 25,
  },
  {
    iata: "SDR",
    nameEn: "Santander Airport",
    nameEs: "Aeropuerto de Santander",
    shortNameEn: "Santander Airport",
    shortNameEs: "Aeropuerto de Santander",
    cityEn: "Santander",
    cityEs: "Santander",
    regionEn: "Cantabria",
    regionEs: "Cantabria",
    slugEn: "santander-airport-transfer",
    slugEs: "traslado-aeropuerto-santander",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: true,
    destinations: [
      { nameEn: "Santander City Centre", nameEs: "Centro de Santander", driveTime: "15 min" },
      { nameEn: "Santillana del Mar", nameEs: "Santillana del Mar", driveTime: "35 min" },
    ],
    nearbyCities: [
      { nameEn: "Camargo", nameEs: "Camargo", driveTime: "10 min" },
    ],
    nearbyAirports: [],
    imageSeed: 26,
  },
  {
    iata: "PNA",
    nameEn: "Pamplona Airport",
    nameEs: "Aeropuerto de Pamplona",
    shortNameEn: "Pamplona Airport",
    shortNameEs: "Aeropuerto de Pamplona",
    cityEn: "Pamplona",
    cityEs: "Pamplona",
    regionEn: "Navarre",
    regionEs: "Navarra",
    slugEn: "pamplona-airport-transfer",
    slugEs: "traslado-aeropuerto-pamplona",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Pamplona City Centre", nameEs: "Centro de Pamplona", driveTime: "15 min" },
    ],
    nearbyCities: [
      { nameEn: "Noáin", nameEs: "Noáin", driveTime: "5 min" },
    ],
    nearbyAirports: [],
    imageSeed: 27,
  },
  {
    iata: "EAS",
    nameEn: "San Sebastián Airport",
    nameEs: "Aeropuerto de San Sebastián",
    shortNameEn: "San Sebastián Airport",
    shortNameEs: "Aeropuerto de San Sebastián",
    cityEn: "San Sebastián",
    cityEs: "San Sebastián",
    regionEn: "Basque Country",
    regionEs: "País Vasco",
    slugEn: "san-sebastian-airport-transfer",
    slugEs: "traslado-aeropuerto-san-sebastian",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "San Sebastián City Centre", nameEs: "Centro de San Sebastián", driveTime: "20 min" },
      { nameEn: "Hondarribia", nameEs: "Hondarribia", driveTime: "15 min" },
    ],
    nearbyCities: [
      { nameEn: "Irún", nameEs: "Irún", driveTime: "15 min" },
    ],
    nearbyAirports: [{ iata: "BIO", driveTime: "1 hr" }],
    imageSeed: 28,
  },
  {
    iata: "SPC",
    nameEn: "La Palma Airport",
    nameEs: "Aeropuerto de La Palma",
    shortNameEn: "La Palma Airport",
    shortNameEs: "Aeropuerto de La Palma",
    cityEn: "Santa Cruz de La Palma",
    cityEs: "Santa Cruz de La Palma",
    regionEn: "Canary Islands",
    regionEs: "Islas Canarias",
    slugEn: "la-palma-airport-transfer",
    slugEs: "traslado-aeropuerto-la-palma",
    isMajor: false,
    islandGroup: "canary",
    hasCruisePort: false,
    destinations: [
      { nameEn: "Santa Cruz de La Palma", nameEs: "Santa Cruz de La Palma", driveTime: "15 min" },
      { nameEn: "Los Cancajos", nameEs: "Los Cancajos", driveTime: "10 min" },
    ],
    nearbyCities: [
      { nameEn: "Breña Alta", nameEs: "Breña Alta", driveTime: "10 min" },
    ],
    nearbyAirports: [],
    imageSeed: 29,
  },
  {
    iata: "GMZ",
    nameEn: "La Gomera Airport",
    nameEs: "Aeropuerto de La Gomera",
    shortNameEn: "La Gomera Airport",
    shortNameEs: "Aeropuerto de La Gomera",
    cityEn: "Alajeró",
    cityEs: "Alajeró",
    regionEn: "Canary Islands",
    regionEs: "Islas Canarias",
    slugEn: "la-gomera-airport-transfer",
    slugEs: "traslado-aeropuerto-la-gomera",
    isMajor: false,
    islandGroup: "canary",
    hasCruisePort: false,
    destinations: [
      { nameEn: "San Sebastián de La Gomera", nameEs: "San Sebastián de La Gomera", driveTime: "30 min" },
      { nameEn: "Valle Gran Rey", nameEs: "Valle Gran Rey", driveTime: "50 min" },
    ],
    nearbyCities: [],
    nearbyAirports: [],
    imageSeed: 30,
  },
  {
    iata: "VDE",
    nameEn: "El Hierro Airport",
    nameEs: "Aeropuerto de El Hierro",
    shortNameEn: "El Hierro Airport",
    shortNameEs: "Aeropuerto de El Hierro",
    cityEn: "Valverde",
    cityEs: "Valverde",
    regionEn: "Canary Islands",
    regionEs: "Islas Canarias",
    slugEn: "el-hierro-airport-transfer",
    slugEs: "traslado-aeropuerto-el-hierro",
    isMajor: false,
    islandGroup: "canary",
    hasCruisePort: false,
    destinations: [
      { nameEn: "Valverde", nameEs: "Valverde", driveTime: "10 min" },
      { nameEn: "La Restinga", nameEs: "La Restinga", driveTime: "45 min" },
    ],
    nearbyCities: [],
    nearbyAirports: [],
    imageSeed: 31,
  },
  {
    iata: "RJL",
    nameEn: "Logroño Airport",
    nameEs: "Aeropuerto de Logroño",
    shortNameEn: "Logroño Airport",
    shortNameEs: "Aeropuerto de Logroño",
    cityEn: "Logroño",
    cityEs: "Logroño",
    regionEn: "La Rioja",
    regionEs: "La Rioja",
    slugEn: "logrono-airport-transfer",
    slugEs: "traslado-aeropuerto-logrono",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Logroño City Centre", nameEs: "Centro de Logroño", driveTime: "15 min" },
      { nameEn: "Haro", nameEs: "Haro", driveTime: "45 min" },
    ],
    nearbyCities: [
      { nameEn: "Agoncillo", nameEs: "Agoncillo", driveTime: "5 min" },
    ],
    nearbyAirports: [],
    imageSeed: 32,
  },
  {
    iata: "VLL",
    nameEn: "Valladolid Airport",
    nameEs: "Aeropuerto de Valladolid",
    shortNameEn: "Valladolid Airport",
    shortNameEs: "Aeropuerto de Valladolid",
    cityEn: "Valladolid",
    cityEs: "Valladolid",
    regionEn: "Castile and León",
    regionEs: "Castilla y León",
    slugEn: "valladolid-airport-transfer",
    slugEs: "traslado-aeropuerto-valladolid",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Valladolid City Centre", nameEs: "Centro de Valladolid", driveTime: "20 min" },
    ],
    nearbyCities: [
      { nameEn: "Villanubla", nameEs: "Villanubla", driveTime: "5 min" },
    ],
    nearbyAirports: [],
    imageSeed: 33,
  },
  {
    iata: "LEN",
    nameEn: "León Airport",
    nameEs: "Aeropuerto de León",
    shortNameEn: "León Airport",
    shortNameEs: "Aeropuerto de León",
    cityEn: "León",
    cityEs: "León",
    regionEn: "Castile and León",
    regionEs: "Castilla y León",
    slugEn: "leon-airport-transfer",
    slugEs: "traslado-aeropuerto-leon",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "León City Centre", nameEs: "Centro de León", driveTime: "20 min" },
    ],
    nearbyCities: [
      { nameEn: "La Virgen del Camino", nameEs: "La Virgen del Camino", driveTime: "10 min" },
    ],
    nearbyAirports: [],
    imageSeed: 34,
  },
  {
    iata: "SLM",
    nameEn: "Salamanca Airport",
    nameEs: "Aeropuerto de Salamanca",
    shortNameEn: "Salamanca Airport",
    shortNameEs: "Aeropuerto de Salamanca",
    cityEn: "Salamanca",
    cityEs: "Salamanca",
    regionEn: "Castile and León",
    regionEs: "Castilla y León",
    slugEn: "salamanca-airport-transfer",
    slugEs: "traslado-aeropuerto-salamanca",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Salamanca City Centre", nameEs: "Centro de Salamanca", driveTime: "25 min" },
    ],
    nearbyCities: [
      { nameEn: "Santa Marta de Tormes", nameEs: "Santa Marta de Tormes", driveTime: "20 min" },
    ],
    nearbyAirports: [],
    imageSeed: 35,
  },
  {
    iata: "BJZ",
    nameEn: "Badajoz Airport",
    nameEs: "Aeropuerto de Badajoz",
    shortNameEn: "Badajoz Airport",
    shortNameEs: "Aeropuerto de Badajoz",
    cityEn: "Badajoz",
    cityEs: "Badajoz",
    regionEn: "Extremadura",
    regionEs: "Extremadura",
    slugEn: "badajoz-airport-transfer",
    slugEs: "traslado-aeropuerto-badajoz",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Badajoz City Centre", nameEs: "Centro de Badajoz", driveTime: "15 min" },
      { nameEn: "Mérida", nameEs: "Mérida", driveTime: "45 min" },
    ],
    nearbyCities: [
      { nameEn: "Talavera la Real", nameEs: "Talavera la Real", driveTime: "10 min" },
    ],
    nearbyAirports: [],
    imageSeed: 36,
  },
  {
    iata: "ODB",
    nameEn: "Córdoba Airport",
    nameEs: "Aeropuerto de Córdoba",
    shortNameEn: "Córdoba Airport",
    shortNameEs: "Aeropuerto de Córdoba",
    cityEn: "Córdoba",
    cityEs: "Córdoba",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    slugEn: "cordoba-airport-transfer",
    slugEs: "traslado-aeropuerto-cordoba",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: false,
    destinations: [
      { nameEn: "Córdoba City Centre", nameEs: "Centro de Córdoba", driveTime: "15 min" },
    ],
    nearbyCities: [
      { nameEn: "Villarrubia", nameEs: "Villarrubia", driveTime: "10 min" },
    ],
    nearbyAirports: [{ iata: "SVQ", driveTime: "1 hr 30 min" }],
    imageSeed: 37,
  },
  {
    iata: "MLN",
    nameEn: "Melilla Airport",
    nameEs: "Aeropuerto de Melilla",
    shortNameEn: "Melilla Airport",
    shortNameEs: "Aeropuerto de Melilla",
    cityEn: "Melilla",
    cityEs: "Melilla",
    regionEn: "Melilla",
    regionEs: "Melilla",
    slugEn: "melilla-airport-transfer",
    slugEs: "traslado-aeropuerto-melilla",
    isMajor: false,
    islandGroup: null,
    hasCruisePort: true,
    destinations: [
      { nameEn: "Melilla City Centre", nameEs: "Centro de Melilla", driveTime: "10 min" },
    ],
    nearbyCities: [],
    nearbyAirports: [],
    imageSeed: 38,
  },
  {
    iata: "JCU",
    nameEn: "Ceuta Heliport",
    nameEs: "Helipuerto de Ceuta",
    shortNameEn: "Ceuta Heliport",
    shortNameEs: "Helipuerto de Ceuta",
    cityEn: "Ceuta",
    cityEs: "Ceuta",
    regionEn: "Ceuta",
    regionEs: "Ceuta",
    slugEn: "ceuta-heliport-transfer",
    slugEs: "traslado-helipuerto-ceuta",
    isMajor: false,
    islandGroup: null,
    heliport: true,
    hasCruisePort: true,
    destinations: [
      { nameEn: "Ceuta City Centre", nameEs: "Centro de Ceuta", driveTime: "10 min" },
    ],
    nearbyCities: [],
    nearbyAirports: [],
    imageSeed: 39,
  },
];

export function findAirportBySlug(locale: "en" | "es", slug: string) {
  return airports.find((airport) => (locale === "es" ? airport.slugEs : airport.slugEn) === slug);
}

export function getAirportPath(locale: "en" | "es", airport: AirportRecord) {
  const slug = locale === "es" ? airport.slugEs : airport.slugEn;
  return locale === "es" ? `/es/${slug}/` : `/${slug}/`;
}
