import type { CityRecord } from "@/lib/cities/types";

export const cities: CityRecord[] = [
  // Featured cities
  {
    slugEn: "barcelona",
    slugEs: "barcelona",
    nameEn: "Barcelona",
    nameEs: "Barcelona",
    regionEn: "Catalonia",
    regionEs: "Cataluña",
    isFeatured: true,
    hasCruisePort: true,
    mainAirportIata: "BCN",
    airportDriveTime: "20 min",
    destinations: [
      { nameEn: "Sitges", nameEs: "Sitges", driveTime: "35 min" },
      { nameEn: "Girona", nameEs: "Girona", driveTime: "1 hr 10 min" },
      { nameEn: "Montserrat", nameEs: "Montserrat", driveTime: "1 hr" },
    ],
    imageSeed: 0,
    blurbEn: "Gothic lanes, Gaudí landmarks, and a Mediterranean cruise port, all within easy reach of El Prat Airport.",
    blurbEs: "Callejuelas góticas, obras de Gaudí y un puerto de cruceros mediterráneo, a un paso del aeropuerto de El Prat.",
  },
  {
    slugEn: "madrid",
    slugEs: "madrid",
    nameEn: "Madrid",
    nameEs: "Madrid",
    regionEn: "Community of Madrid",
    regionEs: "Comunidad de Madrid",
    isFeatured: true,
    hasCruisePort: false,
    mainAirportIata: "MAD",
    airportDriveTime: "30 min",
    destinations: [
      { nameEn: "Toledo", nameEs: "Toledo", driveTime: "1 hr" },
      { nameEn: "Segovia", nameEs: "Segovia", driveTime: "1 hr 20 min" },
      { nameEn: "Ávila", nameEs: "Ávila", driveTime: "1 hr 10 min" },
    ],
    imageSeed: 1,
    blurbEn: "Spain's capital, with Plaza Mayor, world-class museums, and easy day trips to Toledo and Segovia.",
    blurbEs: "La capital de España, con la Plaza Mayor, museos de talla mundial y excursiones fáciles a Toledo y Segovia.",
  },
  {
    slugEn: "valencia",
    slugEs: "valencia",
    nameEn: "Valencia",
    nameEs: "Valencia",
    regionEn: "Valencian Community",
    regionEs: "Comunidad Valenciana",
    isFeatured: true,
    hasCruisePort: true,
    mainAirportIata: "VLC",
    airportDriveTime: "25 min",
    destinations: [
      { nameEn: "Sagunto", nameEs: "Sagunto", driveTime: "35 min" },
      { nameEn: "Albufera Natural Park", nameEs: "Parque Natural de la Albufera", driveTime: "25 min" },
      { nameEn: "Xàtiva", nameEs: "Xàtiva", driveTime: "1 hr" },
    ],
    imageSeed: 2,
    blurbEn: "Futuristic architecture, beaches, and a lively port city on Spain's eastern coast.",
    blurbEs: "Arquitectura futurista, playas y una ciudad portuaria animada en la costa este de España.",
  },
  {
    slugEn: "malaga",
    slugEs: "malaga",
    nameEn: "Málaga",
    nameEs: "Málaga",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    isFeatured: true,
    hasCruisePort: true,
    mainAirportIata: "AGP",
    airportDriveTime: "20 min",
    destinations: [
      { nameEn: "Marbella", nameEs: "Marbella", driveTime: "40 min" },
      { nameEn: "Ronda", nameEs: "Ronda", driveTime: "1 hr 30 min" },
      { nameEn: "Nerja", nameEs: "Nerja", driveTime: "1 hr" },
    ],
    imageSeed: 3,
    blurbEn: "Gateway to the Costa del Sol, with a cruise port and quick transfers to Marbella and Ronda.",
    blurbEs: "Puerta de entrada a la Costa del Sol, con puerto de cruceros y traslados rápidos a Marbella y Ronda.",
  },
  {
    slugEn: "seville",
    slugEs: "sevilla",
    nameEn: "Seville",
    nameEs: "Sevilla",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    isFeatured: true,
    hasCruisePort: false,
    mainAirportIata: "SVQ",
    airportDriveTime: "20 min",
    destinations: [
      { nameEn: "Córdoba", nameEs: "Córdoba", driveTime: "1 hr 30 min" },
      { nameEn: "Cádiz", nameEs: "Cádiz", driveTime: "1 hr 20 min" },
      { nameEn: "Carmona", nameEs: "Carmona", driveTime: "35 min" },
    ],
    imageSeed: 4,
    blurbEn: "Flamenco, tapas, and Andalusian architecture, with day trips to Córdoba and Cádiz.",
    blurbEs: "Flamenco, tapas y arquitectura andaluza, con excursiones a Córdoba y Cádiz.",
  },
  {
    slugEn: "alicante",
    slugEs: "alicante",
    nameEn: "Alicante",
    nameEs: "Alicante",
    regionEn: "Valencian Community",
    regionEs: "Comunidad Valenciana",
    isFeatured: true,
    hasCruisePort: true,
    mainAirportIata: "ALC",
    airportDriveTime: "20 min",
    destinations: [
      { nameEn: "Benidorm", nameEs: "Benidorm", driveTime: "45 min" },
      { nameEn: "Elche", nameEs: "Elche", driveTime: "25 min" },
      { nameEn: "Altea", nameEs: "Altea", driveTime: "50 min" },
    ],
    imageSeed: 5,
    blurbEn: "A Costa Blanca hub with a cruise port and short transfers to Benidorm and Elche.",
    blurbEs: "Un núcleo de la Costa Blanca con puerto de cruceros y traslados cortos a Benidorm y Elche.",
  },
  {
    slugEn: "bilbao",
    slugEs: "bilbao",
    nameEn: "Bilbao",
    nameEs: "Bilbao",
    regionEn: "Basque Country",
    regionEs: "País Vasco",
    isFeatured: true,
    hasCruisePort: false,
    mainAirportIata: "BIO",
    airportDriveTime: "20 min",
    destinations: [
      { nameEn: "San Sebastián", nameEs: "San Sebastián", driveTime: "1 hr" },
      { nameEn: "Guernica", nameEs: "Guernica", driveTime: "35 min" },
      { nameEn: "Vitoria-Gasteiz", nameEs: "Vitoria-Gasteiz", driveTime: "1 hr" },
    ],
    imageSeed: 6,
    blurbEn: "Basque culture and cuisine, with easy transfers to San Sebastián along the coast.",
    blurbEs: "Cultura y gastronomía vascas, con traslados fáciles a San Sebastián por la costa.",
  },
  {
    slugEn: "granada",
    slugEs: "granada",
    nameEn: "Granada",
    nameEs: "Granada",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    isFeatured: true,
    hasCruisePort: false,
    mainAirportIata: "GRX",
    airportDriveTime: "35 min",
    destinations: [
      { nameEn: "Sierra Nevada", nameEs: "Sierra Nevada", driveTime: "45 min" },
      { nameEn: "Nerja", nameEs: "Nerja", driveTime: "1 hr 10 min" },
      { nameEn: "Alhama de Granada", nameEs: "Alhama de Granada", driveTime: "1 hr" },
    ],
    imageSeed: 7,
    blurbEn: "Home to the Alhambra, with mountain views and quick access to Sierra Nevada.",
    blurbEs: "Sede de la Alhambra, con vistas a la montaña y acceso rápido a Sierra Nevada.",
  },
  {
    slugEn: "marbella",
    slugEs: "marbella",
    nameEn: "Marbella",
    nameEs: "Marbella",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    isFeatured: true,
    hasCruisePort: false,
    mainAirportIata: "AGP",
    airportDriveTime: "40 min",
    destinations: [
      { nameEn: "Puerto Banús", nameEs: "Puerto Banús", driveTime: "10 min" },
      { nameEn: "Ronda", nameEs: "Ronda", driveTime: "1 hr" },
      { nameEn: "Estepona", nameEs: "Estepona", driveTime: "25 min" },
    ],
    imageSeed: 8,
    blurbEn: "Costa del Sol glamour, marinas, and golf courses, a short transfer from Málaga Airport.",
    blurbEs: "Glamour, puertos deportivos y campos de golf en la Costa del Sol, a poca distancia del aeropuerto de Málaga.",
  },
  {
    slugEn: "ibiza",
    slugEs: "ibiza",
    nameEn: "Ibiza Town",
    nameEs: "Ciudad de Ibiza",
    regionEn: "Balearic Islands",
    regionEs: "Islas Baleares",
    isFeatured: true,
    hasCruisePort: true,
    mainAirportIata: "IBZ",
    airportDriveTime: "15 min",
    destinations: [
      { nameEn: "San Antonio", nameEs: "San Antonio", driveTime: "20 min" },
      { nameEn: "Santa Eulalia", nameEs: "Santa Eulalia", driveTime: "20 min" },
      { nameEn: "Formentera (via ferry)", nameEs: "Formentera (en ferry)", driveTime: "10 min to port" },
    ],
    imageSeed: 9,
    blurbEn: "Whitewashed streets, a legendary nightlife scene, and a cruise port on the Balearic Sea.",
    blurbEs: "Calles encaladas, una vida nocturna legendaria y un puerto de cruceros en el mar Balear.",
  },
  {
    slugEn: "palma",
    slugEs: "palma",
    nameEn: "Palma de Mallorca",
    nameEs: "Palma de Mallorca",
    regionEn: "Balearic Islands",
    regionEs: "Islas Baleares",
    isFeatured: true,
    hasCruisePort: true,
    mainAirportIata: "PMI",
    airportDriveTime: "15 min",
    destinations: [
      { nameEn: "Sóller", nameEs: "Sóller", driveTime: "40 min" },
      { nameEn: "Valldemossa", nameEs: "Valldemossa", driveTime: "30 min" },
      { nameEn: "Alcúdia", nameEs: "Alcúdia", driveTime: "50 min" },
    ],
    imageSeed: 10,
    blurbEn: "Mallorca's capital, with a cruise port, old town, and easy access to the Tramuntana mountains.",
    blurbEs: "Capital de Mallorca, con puerto de cruceros, casco antiguo y fácil acceso a la Sierra de Tramuntana.",
  },
  {
    slugEn: "zaragoza",
    slugEs: "zaragoza",
    nameEn: "Zaragoza",
    nameEs: "Zaragoza",
    regionEn: "Aragon",
    regionEs: "Aragón",
    isFeatured: true,
    hasCruisePort: false,
    mainAirportIata: "ZAZ",
    airportDriveTime: "20 min",
    destinations: [
      { nameEn: "Monasterio de Piedra", nameEs: "Monasterio de Piedra", driveTime: "1 hr 20 min" },
      { nameEn: "Huesca", nameEs: "Huesca", driveTime: "1 hr" },
      { nameEn: "Tarazona", nameEs: "Tarazona", driveTime: "1 hr" },
    ],
    imageSeed: 11,
    blurbEn: "A historic Aragonese capital, well placed between Madrid and Barcelona.",
    blurbEs: "Una histórica capital aragonesa, bien situada entre Madrid y Barcelona.",
  },

  // Additional cities
  {
    slugEn: "almeria",
    slugEs: "almeria",
    nameEn: "Almería",
    nameEs: "Almería",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "LEI",
    airportDriveTime: "15 min",
    destinations: [
      { nameEn: "Cabo de Gata", nameEs: "Cabo de Gata", driveTime: "40 min" },
      { nameEn: "Mojácar", nameEs: "Mojácar", driveTime: "1 hr" },
    ],
    imageSeed: 12,
  },
  {
    slugEn: "avila",
    slugEs: "avila",
    nameEn: "Ávila",
    nameEs: "Ávila",
    regionEn: "Castile and León",
    regionEs: "Castilla y León",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "MAD",
    airportDriveTime: "1 hr 10 min",
    destinations: [
      { nameEn: "Segovia", nameEs: "Segovia", driveTime: "45 min" },
      { nameEn: "Salamanca", nameEs: "Salamanca", driveTime: "1 hr 15 min" },
    ],
    imageSeed: 13,
  },
  {
    slugEn: "burgos",
    slugEs: "burgos",
    nameEn: "Burgos",
    nameEs: "Burgos",
    regionEn: "Castile and León",
    regionEs: "Castilla y León",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "VLL",
    airportDriveTime: "1 hr 15 min",
    destinations: [
      { nameEn: "Covarrubias", nameEs: "Covarrubias", driveTime: "45 min" },
      { nameEn: "Atapuerca", nameEs: "Atapuerca", driveTime: "20 min" },
    ],
    imageSeed: 14,
  },
  {
    slugEn: "cadiz",
    slugEs: "cadiz",
    nameEn: "Cádiz",
    nameEs: "Cádiz",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    isFeatured: false,
    hasCruisePort: true,
    mainAirportIata: "XRY",
    airportDriveTime: "45 min",
    destinations: [
      { nameEn: "Jerez de la Frontera", nameEs: "Jerez de la Frontera", driveTime: "40 min" },
      { nameEn: "Tarifa", nameEs: "Tarifa", driveTime: "1 hr" },
    ],
    imageSeed: 15,
  },
  {
    slugEn: "cordoba",
    slugEs: "cordoba",
    nameEn: "Córdoba",
    nameEs: "Córdoba",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "SVQ",
    airportDriveTime: "1 hr 30 min",
    destinations: [
      { nameEn: "Medina Azahara", nameEs: "Medina Azahara", driveTime: "15 min" },
      { nameEn: "Priego de Córdoba", nameEs: "Priego de Córdoba", driveTime: "1 hr" },
    ],
    imageSeed: 16,
  },
  {
    slugEn: "cuenca",
    slugEs: "cuenca",
    nameEn: "Cuenca",
    nameEs: "Cuenca",
    regionEn: "Castile-La Mancha",
    regionEs: "Castilla-La Mancha",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "MAD",
    airportDriveTime: "1 hr 45 min",
    destinations: [
      { nameEn: "Ciudad Encantada", nameEs: "Ciudad Encantada", driveTime: "35 min" },
      { nameEn: "Toledo", nameEs: "Toledo", driveTime: "1 hr 40 min" },
    ],
    imageSeed: 17,
  },
  {
    slugEn: "toledo",
    slugEs: "toledo",
    nameEn: "Toledo",
    nameEs: "Toledo",
    regionEn: "Castile-La Mancha",
    regionEs: "Castilla-La Mancha",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "MAD",
    airportDriveTime: "1 hr",
    destinations: [
      { nameEn: "Aranjuez", nameEs: "Aranjuez", driveTime: "35 min" },
      { nameEn: "Consuegra", nameEs: "Consuegra", driveTime: "40 min" },
    ],
    imageSeed: 18,
  },
  {
    slugEn: "segovia",
    slugEs: "segovia",
    nameEn: "Segovia",
    nameEs: "Segovia",
    regionEn: "Castile and León",
    regionEs: "Castilla y León",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "MAD",
    airportDriveTime: "1 hr 20 min",
    destinations: [
      { nameEn: "La Granja de San Ildefonso", nameEs: "La Granja de San Ildefonso", driveTime: "15 min" },
      { nameEn: "Ávila", nameEs: "Ávila", driveTime: "45 min" },
    ],
    imageSeed: 19,
  },
  {
    slugEn: "salamanca",
    slugEs: "salamanca",
    nameEn: "Salamanca",
    nameEs: "Salamanca",
    regionEn: "Castile and León",
    regionEs: "Castilla y León",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "SLM",
    airportDriveTime: "25 min",
    destinations: [
      { nameEn: "Ciudad Rodrigo", nameEs: "Ciudad Rodrigo", driveTime: "1 hr" },
      { nameEn: "Ávila", nameEs: "Ávila", driveTime: "1 hr 15 min" },
    ],
    imageSeed: 20,
  },
  {
    slugEn: "san-sebastian",
    slugEs: "san-sebastian",
    nameEn: "San Sebastián",
    nameEs: "San Sebastián",
    regionEn: "Basque Country",
    regionEs: "País Vasco",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "EAS",
    airportDriveTime: "25 min",
    destinations: [
      { nameEn: "Hondarribia", nameEs: "Hondarribia", driveTime: "25 min" },
      { nameEn: "Bilbao", nameEs: "Bilbao", driveTime: "1 hr" },
    ],
    imageSeed: 21,
  },
  {
    slugEn: "santander",
    slugEs: "santander",
    nameEn: "Santander",
    nameEs: "Santander",
    regionEn: "Cantabria",
    regionEs: "Cantabria",
    isFeatured: false,
    hasCruisePort: true,
    mainAirportIata: "SDR",
    airportDriveTime: "20 min",
    destinations: [
      { nameEn: "Santillana del Mar", nameEs: "Santillana del Mar", driveTime: "35 min" },
      { nameEn: "Comillas", nameEs: "Comillas", driveTime: "45 min" },
    ],
    imageSeed: 22,
  },
  {
    slugEn: "valladolid",
    slugEs: "valladolid",
    nameEn: "Valladolid",
    nameEs: "Valladolid",
    regionEn: "Castile and León",
    regionEs: "Castilla y León",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "VLL",
    airportDriveTime: "25 min",
    destinations: [
      { nameEn: "Tordesillas", nameEs: "Tordesillas", driveTime: "30 min" },
      { nameEn: "Medina del Campo", nameEs: "Medina del Campo", driveTime: "35 min" },
    ],
    imageSeed: 23,
  },
  {
    slugEn: "leon",
    slugEs: "leon",
    nameEn: "León",
    nameEs: "León",
    regionEn: "Castile and León",
    regionEs: "Castilla y León",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "LEN",
    airportDriveTime: "25 min",
    destinations: [
      { nameEn: "Astorga", nameEs: "Astorga", driveTime: "45 min" },
      { nameEn: "Ponferrada", nameEs: "Ponferrada", driveTime: "1 hr" },
    ],
    imageSeed: 24,
  },
  {
    slugEn: "girona",
    slugEs: "girona",
    nameEn: "Girona",
    nameEs: "Girona",
    regionEn: "Catalonia",
    regionEs: "Cataluña",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "GRO",
    airportDriveTime: "25 min",
    destinations: [
      { nameEn: "Figueres", nameEs: "Figueres", driveTime: "40 min" },
      { nameEn: "Costa Brava", nameEs: "Costa Brava", driveTime: "35 min" },
    ],
    imageSeed: 25,
  },
  {
    slugEn: "tarragona",
    slugEs: "tarragona",
    nameEn: "Tarragona",
    nameEs: "Tarragona",
    regionEn: "Catalonia",
    regionEs: "Cataluña",
    isFeatured: false,
    hasCruisePort: true,
    mainAirportIata: "REU",
    airportDriveTime: "20 min",
    destinations: [
      { nameEn: "PortAventura", nameEs: "PortAventura", driveTime: "20 min" },
      { nameEn: "Sitges", nameEs: "Sitges", driveTime: "35 min" },
    ],
    imageSeed: 26,
  },
  {
    slugEn: "murcia",
    slugEs: "murcia",
    nameEn: "Murcia",
    nameEs: "Murcia",
    regionEn: "Region of Murcia",
    regionEs: "Región de Murcia",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "RMU",
    airportDriveTime: "25 min",
    destinations: [
      { nameEn: "Cartagena", nameEs: "Cartagena", driveTime: "45 min" },
      { nameEn: "La Manga del Mar Menor", nameEs: "La Manga del Mar Menor", driveTime: "1 hr" },
    ],
    imageSeed: 27,
  },
  {
    slugEn: "santiago-de-compostela",
    slugEs: "santiago-de-compostela",
    nameEn: "Santiago de Compostela",
    nameEs: "Santiago de Compostela",
    regionEn: "Galicia",
    regionEs: "Galicia",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "SCQ",
    airportDriveTime: "25 min",
    destinations: [
      { nameEn: "A Coruña", nameEs: "A Coruña", driveTime: "50 min" },
      { nameEn: "Padrón", nameEs: "Padrón", driveTime: "20 min" },
    ],
    imageSeed: 28,
  },
  {
    slugEn: "vigo",
    slugEs: "vigo",
    nameEn: "Vigo",
    nameEs: "Vigo",
    regionEn: "Galicia",
    regionEs: "Galicia",
    isFeatured: false,
    hasCruisePort: true,
    mainAirportIata: "VGO",
    airportDriveTime: "20 min",
    destinations: [
      { nameEn: "Islas Cíes", nameEs: "Islas Cíes", driveTime: "30 min to port" },
      { nameEn: "Pontevedra", nameEs: "Pontevedra", driveTime: "30 min" },
    ],
    imageSeed: 29,
  },
  {
    slugEn: "a-coruna",
    slugEs: "a-coruna",
    nameEn: "A Coruña",
    nameEs: "A Coruña",
    regionEn: "Galicia",
    regionEs: "Galicia",
    isFeatured: false,
    hasCruisePort: true,
    mainAirportIata: "LCG",
    airportDriveTime: "15 min",
    destinations: [
      { nameEn: "Santiago de Compostela", nameEs: "Santiago de Compostela", driveTime: "50 min" },
      { nameEn: "Costa da Morte", nameEs: "Costa da Morte", driveTime: "45 min" },
    ],
    imageSeed: 30,
  },
  {
    slugEn: "pamplona",
    slugEs: "pamplona",
    nameEn: "Pamplona",
    nameEs: "Pamplona",
    regionEn: "Navarre",
    regionEs: "Navarra",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "PNA",
    airportDriveTime: "15 min",
    destinations: [
      { nameEn: "Olite", nameEs: "Olite", driveTime: "40 min" },
      { nameEn: "San Sebastián", nameEs: "San Sebastián", driveTime: "1 hr" },
    ],
    imageSeed: 31,
  },
  {
    slugEn: "logrono",
    slugEs: "logrono",
    nameEn: "Logroño",
    nameEs: "Logroño",
    regionEn: "La Rioja",
    regionEs: "La Rioja",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "RJL",
    airportDriveTime: "20 min",
    destinations: [
      { nameEn: "Haro", nameEs: "Haro", driveTime: "45 min" },
      { nameEn: "San Millán de la Cogolla", nameEs: "San Millán de la Cogolla", driveTime: "1 hr" },
    ],
    imageSeed: 32,
  },
  {
    slugEn: "caceres",
    slugEs: "caceres",
    nameEn: "Cáceres",
    nameEs: "Cáceres",
    regionEn: "Extremadura",
    regionEs: "Extremadura",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "BJZ",
    airportDriveTime: "1 hr",
    destinations: [
      { nameEn: "Trujillo", nameEs: "Trujillo", driveTime: "45 min" },
      { nameEn: "Mérida", nameEs: "Mérida", driveTime: "1 hr" },
    ],
    imageSeed: 33,
  },
  {
    slugEn: "huelva",
    slugEs: "huelva",
    nameEn: "Huelva",
    nameEs: "Huelva",
    regionEn: "Andalusia",
    regionEs: "Andalucía",
    isFeatured: false,
    hasCruisePort: false,
    mainAirportIata: "SVQ",
    airportDriveTime: "1 hr",
    destinations: [
      { nameEn: "Doñana National Park", nameEs: "Parque Nacional de Doñana", driveTime: "40 min" },
      { nameEn: "Punta Umbría", nameEs: "Punta Umbría", driveTime: "25 min" },
    ],
    imageSeed: 34,
  },
  {
    slugEn: "cartagena",
    slugEs: "cartagena",
    nameEn: "Cartagena",
    nameEs: "Cartagena",
    regionEn: "Region of Murcia",
    regionEs: "Región de Murcia",
    isFeatured: false,
    hasCruisePort: true,
    mainAirportIata: "RMU",
    airportDriveTime: "45 min",
    destinations: [
      { nameEn: "La Manga del Mar Menor", nameEs: "La Manga del Mar Menor", driveTime: "30 min" },
      { nameEn: "Murcia", nameEs: "Murcia", driveTime: "45 min" },
    ],
    imageSeed: 35,
  },
];

export function findCityBySlug(locale: "en" | "es", slug: string) {
  return cities.find((city) => (locale === "es" ? city.slugEs : city.slugEn) === slug);
}

export function getCityPath(locale: "en" | "es", city: CityRecord) {
  const slug = locale === "es" ? city.slugEs : city.slugEn;
  return locale === "es" ? `/es/${slug}/` : `/${slug}/`;
}
